#!/usr/bin/env python3
"""
Macroeconomics (Gwartney 18e) practice quiz - Chapters 1, 2, 5, 6, 7, 8, 9, 10 (200 questions, 25 per chapter)
Run:  python3 econ_quiz.py
No installs needed (standard library only).

Features
- Pick which chapters to practice
- Answer options are shuffled every time, so you learn the idea, not the letter
- Questions you miss come back at the end of the round until you get them right
- Missed questions are saved to ~/.econ_quiz_missed.json so you can do a
  "weak spots" round later
"""

import json
import os
import random
import textwrap

SAVE_FILE = os.path.expanduser("~/.econ_quiz_missed.json")

# In every question, the FIRST option is the correct one (they get shuffled on display).
QUESTIONS = [
    # ---------------- Chapter 1: The Economic Approach ----------------
    {"ch": 1, "q": "What is the opportunity cost of a choice?",
     "opts": ["The highest valued alternative that is sacrificed",
              "The total dollar price paid for the option",
              "The sum of all alternatives given up",
              "The cost of acquiring information about the option"],
     "exp": "Opportunity cost is the single highest-valued alternative you give up, not the sum of all alternatives. It's subjective and varies across people."},
    {"ch": 1, "q": "Which statement is NORMATIVE?",
     "opts": ["The inflation rate should be lower.",
              "The inflation rate rises when the money supply is increased.",
              "The earth is made of marshmallows.",
              "If gas prices rise, people will buy less gas."],
     "exp": "Normative = 'what ought to be' (should/ought), can't be proven true or false. Positive statements are testable even if false, like the marshmallow one."},
    {"ch": 1, "q": "Assuming that what is true for an individual must also be true for the whole group is called:",
     "opts": ["The fallacy of composition",
              "Violation of ceteris paribus",
              "Association is not causation",
              "The secondary effects pitfall"],
     "exp": "Fallacy of composition. Watch for it when moving from micro (individuals/firms) to macro (the whole economy)."},
    {"ch": 1, "q": "'Ceteris paribus' means:",
     "opts": ["Other things held constant",
              "At the margin",
              "Buyer beware",
              "Value is subjective"],
     "exp": "Ceteris paribus = other things constant. Failing to hold other things constant can lead to wrong conclusions about cause and effect."},
    {"ch": 1, "q": "When price is used to ration a good, who gets it?",
     "opts": ["Those willing and able to give up other things (pay the price)",
              "Those who arrive first",
              "Those with the most political influence",
              "Those who need it most"],
     "exp": "Price rationing allocates to those willing to give up other things, and it creates an incentive to earn income. First-come-first-served rewards waiting; government rationing rewards political status."},
    {"ch": 1, "q": "Economists say the test of a theory is:",
     "opts": ["Its ability to predict",
              "Whether experts agree with it",
              "Whether its assumptions are realistic",
              "Whether it is supported by good intentions"],
     "exp": "Principle 8: the test of a theory is its ability to predict real-world outcomes."},

    # ---------------- Chapter 2: Some Tools of the Economist ----------------
    {"ch": 2, "q": "A point INSIDE the production possibilities curve represents:",
     "opts": ["An inefficient use of resources",
              "An unattainable combination of output",
              "Full and efficient use of resources",
              "Economic growth"],
     "exp": "Inside = inefficient; you could get more of one good without giving up any of the other. On the curve = efficient. Outside = unattainable with current resources."},
    {"ch": 2, "q": "Which of these would NOT shift the PPC outward?",
     "opts": ["Moving resources from producing food to producing clothing",
              "An advancement in technology",
              "An increase in the economy's resource base",
              "Improvements in the rules under which the economy functions"],
     "exp": "Reallocating resources moves you ALONG the curve. The four outward shifters: more resources, better technology, improved rules/institutions, and working harder (giving up leisure)."},
    {"ch": 2, "q": "The law of comparative advantage says joint output is greatest when each good is produced by:",
     "opts": ["The low opportunity cost producer",
              "The producer who can make the most of it in absolute terms",
              "The producer with the most resources",
              "Whoever values the good most"],
     "exp": "Comparative advantage is about LOWER OPPORTUNITY COST, not absolute ability. It applies to individuals, firms, regions, and nations."},
    {"ch": 2, "q": "An economy that chooses more investment goods and fewer consumption goods today will likely:",
     "opts": ["See its PPC shift outward more in the future",
              "See its PPC shift inward in the future",
              "Move to a point inside its PPC",
              "Have no change in future production possibilities"],
     "exp": "Investing now (buildings, equipment, training) means greater future output, so the PPC shifts farther out compared with a high-consumption choice."},
    {"ch": 2, "q": "Middlemen (like your local grocer) are valuable mainly because they:",
     "opts": ["Reduce transaction costs",
              "Increase the price of goods",
              "Create property rights",
              "Eliminate opportunity costs"],
     "exp": "Middlemen reduce the time, effort, and resources needed to search out, negotiate, and complete an exchange (transaction costs)."},
    {"ch": 2, "q": "Which is NOT one of the three parts of private property rights?",
     "opts": ["The right to have the government set the property's price",
              "The right to exclusive use",
              "Legal protection against invaders",
              "The right to transfer it to another"],
     "exp": "Private property rights = exclusive use, legal protection against invasion, and the right to transfer (sell, rent, lease, etc.)."},
    {"ch": 2, "q": "When a voluntary exchange occurs:",
     "opts": ["Both parties expect to be made better off",
              "One party gains exactly what the other loses",
              "Value is only transferred, not created",
              "The good's objective value stays fixed"],
     "exp": "Mutual gain is the foundation of trade. Moving goods to people who value them more creates value."},

    # ---------------- Chapter 5: Difficult Cases for the Market ----------------
    {"ch": 5, "q": "The economically efficient level of an activity is where:",
     "opts": ["Marginal benefit equals marginal cost",
              "Marginal benefit is at its maximum",
              "Total cost is minimized",
              "Marginal cost is zero"],
     "exp": "Expand an activity as long as MB > MC; stop where MB = MC (Q2 on the graph). Below that you skip worthwhile units; beyond it MC > MB."},
    {"ch": 5, "q": "When external COSTS (negative externality) are present, the market will produce:",
     "opts": ["Too many units at too low a price",
              "Too few units at too high a price",
              "Too few units at too low a price",
              "The efficient quantity"],
     "exp": "The supply curve understates the true cost, so output is too high and price too low. Including all costs shifts supply left (S2): lower Q, higher P."},
    {"ch": 5, "q": "When external BENEFITS (positive externality) are present, the market will usually produce:",
     "opts": ["Too few units",
              "Too many units",
              "The efficient quantity",
              "Nothing at all"],
     "exp": "The demand curve understates the total value, so units worth more than they cost may not get produced. Counting all benefits shifts demand right."},
    {"ch": 5, "q": "The two defining characteristics of a public good are:",
     "opts": ["Nonrival in consumption and nonexcludable",
              "Produced by government and free of charge",
              "Rival in consumption and excludable",
              "Low cost and high demand"],
     "exp": "It's the good's characteristics, not who produces it. Examples: national defense, broadcast signals, mosquito abatement."},
    {"ch": 5, "q": "A person who receives the benefits of a good without helping pay for it is a:",
     "opts": ["Free rider",
              "Rent seeker",
              "Middleman",
              "Crony capitalist"],
     "exp": "Because nonpayers can't be excluded from public goods, people have an incentive to free ride, so too little of the good gets produced."},
    {"ch": 5, "q": "Which is NOT one of the four reasons the invisible hand (markets) may fail?",
     "opts": ["The special interest effect",
              "Lack of competition",
              "Externalities",
              "Poor information"],
     "exp": "Market failure: lack of competition, externalities, public goods, poor information. The special interest effect is a source of GOVERNMENT failure (Ch. 6)."},
    {"ch": 5, "q": "When competition is absent, sellers tend to:",
     "opts": ["Restrict output and raise prices",
              "Expand output and lower prices",
              "Produce the efficient quantity",
              "Create external benefits"],
     "exp": "Restricted supply (S2) gives Q2 < Q1 and P2 > P1: too few units at too high a price."},
    {"ch": 5, "q": "Protecting people and property and enforcing contracts is government's:",
     "opts": ["Protective function",
              "Productive function",
              "Redistributive function",
              "Regulatory function"],
     "exp": "Protective = security, rules, contract enforcement. Productive = providing goods hard to supply through markets (and a stable monetary environment)."},

    # ---------------- Chapter 6: The Economics of Political Action ----------------
    {"ch": 6, "q": "Voters having little incentive to become informed because their single vote is unlikely to be decisive is the:",
     "opts": ["Rational ignorance effect",
              "Shortsightedness effect",
              "Special interest effect",
              "Bundle purchase problem"],
     "exp": "Rational ignorance: getting informed is costly and one vote rarely changes the outcome, so many voters stay uninformed on many issues."},
    {"ch": 6, "q": "Representative government is biased toward adopting INEFFICIENT projects when:",
     "opts": ["Benefits are concentrated and costs are widespread",
              "Benefits and costs are both widespread",
              "Benefits are widespread and costs are concentrated",
              "Benefits and costs are both concentrated"],
     "exp": "Type 2: concentrated benefits + widespread costs = special interest effect. (Type 4, widespread benefits + concentrated costs, tends to REJECT productive projects.)"},
    {"ch": 6, "q": "Road project: benefits are Adams $20, Chan $12, Green $4, Lee $2, Diaz $2 (total $40). Under Plan A everyone pays $5 tax. What happens in a majority vote?",
     "opts": ["It fails 3 to 2, even though it's efficient",
              "It passes 3 to 2",
              "It passes unanimously",
              "It fails unanimously because it's inefficient"],
     "exp": "Only Adams and Chan gain more than $5. Green, Lee, Diaz vote no, so it fails 3-2 even though total benefits ($40) exceed costs ($25). Under Plan B (taxes proportional to benefits) it passes unanimously."},
    {"ch": 6, "q": "Politicians exchanging support on one issue for support on another is called:",
     "opts": ["Logrolling",
              "Pork-barrel legislation",
              "Rent seeking",
              "Crony capitalism"],
     "exp": "Logrolling = vote trading. Pork-barrel legislation = bundling many local spending projects into one bill."},
    {"ch": 6, "q": "Why do politicians find debt financing attractive, according to public choice analysis?",
     "opts": ["The shortsightedness effect: current benefits now, hard-to-see costs later",
              "The rational ignorance effect makes debt free",
              "Debt-financed projects are always efficient",
              "Bureaucrats prefer smaller budgets"],
     "exp": "Shortsightedness effect: bias toward clearly defined current benefits with future costs that are hard to identify."},
    {"ch": 6, "q": "Actions by groups trying to use the political process to redistribute income to themselves are called:",
     "opts": ["Rent (favor) seeking",
              "Entrepreneurship",
              "Logrolling",
              "Comparative advantage"],
     "exp": "Rent seeking diverts resources from productive activity, so output falls below potential."},
    {"ch": 6, "q": "The 'bootleggers and Baptists' strategy refers to:",
     "opts": ["Self-interested action packaged as moral behavior",
              "Voters trading votes across districts",
              "Bureaucrats seeking larger budgets",
              "Markets failing to provide public goods"],
     "exp": "Rent seekers frame favors as child safety, saving family farms, etc. Example: Mattel and the 2008 Consumer Product Safety Improvement Act."},
    {"ch": 6, "q": "The U.S. sugar program (concentrated gains for ~20,000 growers, ~$25 cost per household) illustrates:",
     "opts": ["The special interest effect",
              "The rational ignorance effect only",
              "A public good",
              "An efficient government program"],
     "exp": "Large personal benefit for a few + small individual cost spread over many = special interest effect. The program persists even though it's counterproductive."},
    {"ch": 6, "q": "Which is a source of GOVERNMENT failure?",
     "opts": ["Weak incentives for operational efficiency",
              "Externalities",
              "Public goods",
              "Lack of competition among sellers"],
     "exp": "Government failure: special interest effect, shortsightedness effect, rent seeking, weak incentives for operational efficiency (no profit motive, no bankruptcy)."},

    # ---------------- Chapter 7: Taking the Nation's Economic Pulse ----------------
    {"ch": 7, "q": "Why are intermediate goods NOT counted in GDP?",
     "opts": ["It would double count their value",
              "They are not produced domestically",
              "They are not sold for money",
              "They are counted in net exports instead"],
     "exp": "Only final goods and services count; the value of intermediate goods is already embodied in the final good."},
    {"ch": 7, "q": "Which is NOT a component of GDP under the EXPENDITURE approach?",
     "opts": ["Employee compensation",
              "Personal consumption",
              "Gross private investment",
              "Net exports"],
     "exp": "Expenditure approach: C + I + G + NX. Employee compensation is part of the resource cost-income approach (with self-employment income, rents, interest, profits)."},
    {"ch": 7, "q": "Nominal GDP is $27,361 billion and the GDP deflator is 122.3 (base year = 100). Real GDP in base-year dollars is about:",
     "opts": ["$22,372 billion", "$33,463 billion", "$27,361 billion", "$24,950 billion"],
     "exp": "Real GDP = Nominal GDP / (Deflator / 100) = 27,361 / 1.223 = about 22,372. (The 2023 figure in 2017 dollars from your slides.)"},
    {"ch": 7, "q": "How does the GDP deflator differ from the CPI?",
     "opts": ["The GDP deflator covers all goods in GDP; the CPI covers only what households buy",
              "The CPI is broader than the GDP deflator",
              "The GDP deflator only measures imported goods",
              "They use the exact same market basket"],
     "exp": "The GDP deflator is broader. It and the chained CPI also adjust for substitution away from goods that got relatively more expensive."},
    {"ch": 7, "q": "Which of these is NOT counted in GDP?",
     "opts": ["A homemaker cooking meals for their own family",
              "A family paying for a streaming subscription",
              "A firm buying new machinery",
              "The government building a highway"],
     "exp": "Household (nonmarket) production isn't counted because there's no market transaction. Other GDP shortcomings: underground economy, leisure, quality changes, 'bads'."},
    {"ch": 7, "q": "A hurricane destroys homes and infrastructure, then rebuilding begins. How is GDP affected?",
     "opts": ["Damages are not subtracted, but recovery spending is added",
              "Damages are subtracted and recovery spending is added",
              "Neither is counted",
              "Damages are subtracted and recovery spending is ignored"],
     "exp": "GDP tracks production, not destruction, so GDP can rise after a disaster. That's one reason GDP isn't a perfect welfare measure."},
    {"ch": 7, "q": "Between 2017 and 2023, nominal GDP rose 39.5%, but real GDP rose only 14.1%. Why?",
     "opts": ["Prices rose about 22% over the period",
              "Population fell",
              "Net exports were negative",
              "Intermediate goods were excluded"],
     "exp": "Nominal growth mixes higher output with higher prices. Deflating removes the price increase (deflator went 100 to 122.3)."},

    # ---------------- Chapter 8: Fluctuations, Unemployment, Inflation ----------------
    {"ch": 8, "q": "Population age 16+ = 250M, employed = 152M, unemployed = 8M. What is the UNEMPLOYMENT rate?",
     "opts": ["5.0%", "3.2%", "5.3%", "64%"],
     "exp": "Unemployment rate = unemployed / labor force. Labor force = 152 + 8 = 160M, so 8/160 = 5%. (Dividing by population is a common trap.)"},
    {"ch": 8, "q": "Same economy: population 16+ = 250M, employed = 152M, unemployed = 8M. What is the LABOR FORCE PARTICIPATION rate?",
     "opts": ["64%", "60.8%", "95%", "5%"],
     "exp": "LFPR = labor force / population 16+ = 160 / 250 = 64%. (152/250 = 60.8% is the employment-population ratio.)"},
    {"ch": 8, "q": "A person working part-time who is diligently searching for a full-time job is classified as:",
     "opts": ["Employed", "Unemployed", "Not in the labor force", "Cyclically unemployed"],
     "exp": "Working at least 1 hour for pay counts as employed, even if they want more hours."},
    {"ch": 8, "q": "A full-time college student who isn't working or looking for work is:",
     "opts": ["Not in the labor force", "Unemployed", "Employed", "Frictionally unemployed"],
     "exp": "Not working and not seeking work = not in the labor force (same for retirees and homemakers)."},
    {"ch": 8, "q": "An auto worker on temporary layoff who expects to be recalled is classified as:",
     "opts": ["Unemployed", "Employed", "Not in the labor force", "Discouraged worker"],
     "exp": "People on layoff waiting to return to a previous job count as unemployed."},
    {"ch": 8, "q": "Frictional unemployment is caused by:",
     "opts": ["Imperfect information as workers and employers search for good matches",
              "Workers' skills not matching available jobs",
              "A recession reducing demand for labor",
              "Not enough jobs for everyone"],
     "exp": "Frictional = job search under imperfect information. Structural = skill mismatch from changing products/technology. Cyclical = business cycle downturns."},
    {"ch": 8, "q": "New technology makes certain skills obsolete, and job openings require skills the unemployed don't have. This is:",
     "opts": ["Structural unemployment", "Frictional unemployment", "Cyclical unemployment", "Seasonal employment"],
     "exp": "Structural unemployment comes from structural changes in the economy that create a skills mismatch."},
    {"ch": 8, "q": "At full employment:",
     "opts": ["Only frictional and structural unemployment remain (no cyclical)",
              "The unemployment rate is zero",
              "Cyclical unemployment is at its peak",
              "Actual GDP is below potential GDP"],
     "exp": "Full employment = natural rate of unemployment, not zero. Actual output equals potential output."},
    {"ch": 8, "q": "During a recession, which is true?",
     "opts": ["Actual GDP is below potential GDP",
              "Actual unemployment is below the natural rate",
              "Employment exceeds full employment",
              "Cyclical unemployment is zero"],
     "exp": "In a recession, actual unemployment rises above the natural rate and actual GDP falls below potential."},
    {"ch": 8, "q": "The CPI was 150 at the end of last year and 157.5 at the end of this year. The inflation rate was:",
     "opts": ["5%", "7.5%", "4.8%", "57.5%"],
     "exp": "Inflation = (157.5 - 150) / 150 x 100 = 7.5 / 150 = 5%."},
    {"ch": 8, "q": "People expected 3% inflation, but prices rose 7%. This is:",
     "opts": ["Inflation higher than anticipated (unanticipated inflation)",
              "Anticipated inflation",
              "Inflation lower than anticipated",
              "Deflation"],
     "exp": "Actual exceeded expected, so 4 points of it was a surprise. Unanticipated inflation is what disrupts long-term contracts."},
    {"ch": 8, "q": "The four phases of the business cycle, in order starting from the top, are:",
     "opts": ["Peak, contraction, recessionary trough, expansion",
              "Expansion, peak, trough, contraction",
              "Peak, trough, contraction, expansion",
              "Contraction, peak, expansion, trough"],
     "exp": "Peak (boom) then contraction then recessionary trough (bottom) then expansion. A depression is a prolonged, very severe recession."},
    {"ch": 8, "q": "Which is NOT a reason high and variable inflation harms the economy?",
     "opts": ["It makes long-term contracts easier to plan",
              "It distorts the information delivered by prices",
              "It reduces investment by increasing risk",
              "People spend more time protecting wealth instead of producing"],
     "exp": "High, variable inflation makes long-term planning HARDER. It's hard to predict, which is exactly the problem."},

    # ---------------- Chapter 9: Basic Macroeconomic Markets ----------------
    {"ch": 9, "q": "Which is NOT a reason the aggregate demand curve slopes downward?",
     "opts": ["A higher price level improves firms' profit margins",
              "A lower price level increases the purchasing power of money",
              "A lower price level lowers interest rates, boosting spending",
              "A lower price level makes domestic goods cheaper relative to foreign goods"],
     "exp": "The profit-margin story explains why SRAS slopes UP. AD slopes down due to the wealth effect, the interest rate effect, and the international substitution effect."},
    {"ch": 9, "q": "Why is the long-run aggregate supply (LRAS) curve vertical?",
     "opts": ["A higher price level doesn't change resources, technology, or institutions",
              "Firms can't change output in the long run",
              "Prices are fixed by contracts in the long run",
              "Aggregate demand is constant in the long run"],
     "exp": "Full-employment output (YF) depends on resources, technology, and institutions, which the price level doesn't change. So output can't be sustainably expanded by higher prices."},
    {"ch": 9, "q": "Why does the SRAS curve slope upward?",
     "opts": ["Some costs are fixed by contracts, so an unexpected price rise boosts profits",
              "Higher prices increase the economy's resource base",
              "Consumers buy more when prices rise",
              "Interest rates fall when prices rise"],
     "exp": "In the short run, wages, interest rates, etc. are locked in by prior contracts, so an unanticipated higher price level widens profit margins and firms expand output."},
    {"ch": 9, "q": "The money interest rate is 11% and expected inflation is 5%. The real interest rate is:",
     "opts": ["6%", "16%", "11%", "2.2%"],
     "exp": "Real interest rate = money interest rate - inflationary premium = 11% - 5% = 6%."},
    {"ch": 9, "q": "If actual inflation turns out HIGHER than anticipated:",
     "opts": ["Borrowers gain at the expense of lenders",
              "Lenders gain at the expense of borrowers",
              "Neither gains, since the interest rate adjusts",
              "Both gain equally"],
     "exp": "Borrowers repay with dollars worth less than expected. If inflation is LOWER than anticipated, lenders gain. Correctly anticipated inflation favors neither."},
    {"ch": 9, "q": "When overall interest rates rise, prices of previously issued bonds:",
     "opts": ["Fall", "Rise", "Stay the same", "Become zero"],
     "exp": "Old bonds pay a fixed rate. When new bonds pay more, the old ones are less attractive, so their price falls. Inverse relationship."},
    {"ch": 9, "q": "With a market-determined exchange rate, a trade deficit is closely linked with:",
     "opts": ["A net inflow of capital", "A net outflow of capital", "A budget surplus", "A trade surplus"],
     "exp": "Imports - Exports = Capital inflow - Capital outflow. A trade deficit (imports > exports) is matched by net capital inflow."},
    {"ch": 9, "q": "When the economy is in long-run equilibrium:",
     "opts": ["Actual unemployment equals the natural rate AND the actual price level equals the anticipated one",
              "Unemployment is zero",
              "Actual GDP exceeds potential GDP",
              "Cyclical unemployment is high"],
     "exp": "Long-run equilibrium: AD, SRAS, and LRAS intersect; output = potential (YF); full employment; expectations about the price level turned out correct."},
    {"ch": 9, "q": "An unanticipated increase in the price level will, in the short run:",
     "opts": ["Expand output and employment",
              "Reduce output and employment",
              "Have no effect on output",
              "Permanently increase potential GDP"],
     "exp": "Real wages and other contracted costs lag, so profits rise and firms expand. In the long run, costs catch up and output returns to potential."},
    {"ch": 9, "q": "Using government taxation and spending to achieve macroeconomic goals is:",
     "opts": ["Fiscal policy", "Monetary policy", "Trade policy", "Rent seeking"],
     "exp": "Fiscal = taxes and spending. Monetary = control of the money supply and credit conditions."},
    {"ch": 9, "q": "Which market coordinates the actions of borrowers and lenders, with the interest rate as its price?",
     "opts": ["Loanable funds market", "Resource market", "Foreign exchange market", "Goods and services market"],
     "exp": "The four key markets: goods & services, resource, loanable funds, foreign exchange."},
    {"ch": 9, "q": "Are trade deficits necessarily bad?",
     "opts": ["It depends on whether the borrowed funds go to productive investment",
              "Yes, always",
              "No, never",
              "Only when the exchange rate is fixed"],
     "exp": "A trade deficit reflects capital inflow (borrowing from foreigners). Productive investment raises future income; funding consumption or unproductive uses lowers it."},

    # ---------------- Chapter 10: Dynamic Change & the AD-AS Model ----------------
    {"ch": 10, "q": "Which of these would shift aggregate demand to the RIGHT?",
     "opts": ["A stock market boom that increases real wealth",
              "An increase in the real interest rate",
              "Growing pessimism among consumers and businesses",
              "An increase in the exchange rate value of the nation's currency"],
     "exp": "AD shifts right with: more real wealth, lower real interest rates, optimism, higher expected inflation, higher incomes abroad, and a LOWER exchange rate value of the currency."},
    {"ch": 10, "q": "A decline in the exchange rate value of the dollar will tend to:",
     "opts": ["Increase AD, because U.S. goods become cheaper to foreigners",
              "Decrease AD, because imports become cheaper",
              "Shift LRAS to the right",
              "Have no effect on AD"],
     "exp": "A weaker dollar makes U.S. exports cheaper and imports pricier, so net exports and AD rise."},
    {"ch": 10, "q": "Which would shift BOTH LRAS and SRAS to the right?",
     "opts": ["An improvement in technology",
              "A temporary spell of favorable weather",
              "A temporary drop in resource prices",
              "A reduction in expected inflation"],
     "exp": "LRAS shifters (resources, technology/productivity, institutions) move SRAS in the same direction too. Weather, temporary resource price changes, and expected inflation shift only SRAS."},
    {"ch": 10, "q": "A drought that temporarily reduces crop output would:",
     "opts": ["Shift SRAS left but leave LRAS unchanged",
              "Shift both LRAS and SRAS left",
              "Shift AD left",
              "Shift LRAS left only"],
     "exp": "Temporary changes in productive capability shift SRAS only. The long-run capacity of the economy isn't altered."},
    {"ch": 10, "q": "Steady, predictable growth from capital formation and better technology will:",
     "opts": ["Shift LRAS right without disrupting macro equilibrium",
              "Cause a recession",
              "Cause an unsustainable boom",
              "Shift only SRAS"],
     "exp": "Anticipated changes let decision makers adjust ahead of time, so equilibrium isn't disrupted. Full-employment output rises from YF1 to YF2."},
    {"ch": 10, "q": "In the SHORT run, an unanticipated increase in AD causes:",
     "opts": ["A higher price level and output above long-run potential",
              "A lower price level and lower output",
              "A higher price level with no change in output",
              "Unemployment above the natural rate"],
     "exp": "Profit margins temporarily improve, output exceeds potential, and unemployment falls BELOW the natural rate (e.g., P105 and Y2 on the slide)."},
    {"ch": 10, "q": "In the LONG run, after an unanticipated increase in AD:",
     "opts": ["Resource prices rise, SRAS shifts left, and output returns to potential at a higher price level",
              "Output stays permanently above potential",
              "Resource prices fall and SRAS shifts right",
              "LRAS shifts right to match the new AD"],
     "exp": "Contracts get renegotiated, costs rise, SRAS shifts left, and you end at full-employment output with a higher price level (P110). The demand boost only expanded output temporarily."},
    {"ch": 10, "q": "After an unanticipated DECREASE in AD, what eventually returns the economy to long-run equilibrium?",
     "opts": ["Lower resource prices and lower real interest rates",
              "Higher resource prices and higher real interest rates",
              "A permanent leftward shift of LRAS",
              "Nothing; the economy stays in recession permanently"],
     "exp": "Weak demand lowers resource prices (SRAS shifts right) and real interest rates fall, stimulating AD. Output returns to potential at a lower price level (P90), but it can be a lengthy, painful process."},
    {"ch": 10, "q": "An unexpected event that temporarily increases or decreases aggregate supply is a:",
     "opts": ["Supply shock", "Demand shock", "Fiscal policy", "Shift in LRAS"],
     "exp": "Supply shocks catch people by surprise. Examples of negative ones: the 2022 Russia-Ukraine war's effect on wheat and energy, Hurricane Katrina."},
    {"ch": 10, "q": "A sharp, unexpected rise in the world price of oil will, in the short run:",
     "opts": ["Shift SRAS left, raising the price level and lowering output",
              "Shift SRAS right, lowering the price level and raising output",
              "Shift AD right, raising both price level and output",
              "Have no effect until LRAS shifts"],
     "exp": "Higher resource costs shift SRAS left: price level up (P110), output down (Y2). If the shock is permanent, LRAS shifts left too; if temporary, SRAS eventually moves back."},
    {"ch": 10, "q": "A temporary bumper crop from good weather would cause:",
     "opts": ["A lower price level and higher current GDP, with LRAS unchanged",
              "A higher price level and lower GDP",
              "A permanent rightward shift in LRAS",
              "A leftward shift in AD"],
     "exp": "Favorable, temporary supply shock: SRAS shifts right, price level falls (P95), output rises to Y2. Because it can't be counted on, LRAS stays put."},
    {"ch": 10, "q": "If the actual rate of inflation is LESS than anticipated, firms will tend to:",
     "opts": ["Incur losses and reduce output",
              "Earn higher profits and expand output",
              "Leave output unchanged",
              "Shift LRAS to the right"],
     "exp": "Lower-than-expected inflation acts like a fall in the price level relative to locked-in costs. Higher-than-expected inflation does the opposite and boosts output."},
    {"ch": 10, "q": "According to the AD-AS model, the two causes of recessions are:",
     "opts": ["Unanticipated reductions in AD and unfavorable supply shocks",
              "Anticipated increases in AD and favorable supply shocks",
              "Steady growth in LRAS and lower interest rates",
              "Higher wealth and consumer optimism"],
     "exp": "Recession = product prices low relative to costs. Booms come from unanticipated increases in AD and favorable supply shocks."},
    {"ch": 10, "q": "During a recession, real interest rates tend to:",
     "opts": ["Fall, which stimulates AD and helps the economy recover",
              "Rise, which deepens the recession",
              "Stay constant",
              "Rise, which stimulates investment"],
     "exp": "The two self-correcting forces: real resource prices and real interest rates. In a recession both fall; in a boom both rise and slow the economy."},
    {"ch": 10, "q": "What caused the 2008-2009 Great Recession in AD-AS terms?",
     "opts": ["Falling housing and stock prices reduced AD, and soaring oil prices reduced SRAS",
              "Rising housing prices increased AD",
              "A permanent improvement in technology shifted LRAS",
              "Falling oil prices increased SRAS"],
     "exp": "Housing prices fell after mid-2006 and stocks plunged in 2008 (less wealth, lower AD), energy prices surged in 2007-08 (lower SRAS), and confidence collapsed (AD fell further)."},
    {"ch": 10, "q": "Which would be MOST likely to throw the U.S. economy into a recession?",
     "opts": ["An unanticipated drop in AD from a sharp decline in consumer confidence",
              "Lower transaction costs from the growth of the Internet",
              "An unanticipated fall in the world price of oil",
              "Steady, anticipated growth in the capital stock"],
     "exp": "Unanticipated AD reductions cause recessions. Lower transaction costs and cheaper oil boost supply (cheaper oil hurts oil-producing states, though)."},
    {"ch": 10, "q": "Over the past several decades, how have U.S. expansions compared with recessions?",
     "opts": ["Expansions have been far lengthier than recessions",
              "Recessions have been longer than expansions",
              "They have been about equal in length",
              "There have been no recessions since 1950"],
     "exp": "E.g., the 2009-2020 expansion lasted 128 months, while most recessions lasted under a year and a half."},
    # ================ Added questions (from the chapter slides) ================
    # These are appended at the end, not inside the chapter sections above, so the
    # question numbers saved in ~/.econ_quiz_missed.json still point to the same questions.
    # ---------------- Chapter 1: The Economic Approach (added) ----------------
    {"ch": 1, "q": "Goods are scarce because:",
     "opts": ["Our desire for them far outstrips their availability from nature",
              "They are always expensive",
              "Governments limit how much can be produced",
              "Businesses produce them inefficiently"],
     "exp": "Scarcity means wants exceed what nature makes available. Even free things like your time are scarce, and scarcity forces us to choose among alternatives."},
    {"ch": 1, "q": "In economics, 'capital' refers to:",
     "opts": ["Human-made resources, like machines and buildings",
              "Money kept in a bank account",
              "Natural resources such as land and minerals",
              "The labor supplied by workers"],
     "exp": "Resources are inputs used to produce goods and services (land, labor, etc.). Capital is the subset of resources that people have made."},
    {"ch": 1, "q": "Rationing is best defined as:",
     "opts": ["Allocating a limited supply of a good among people who want more of it",
              "Charging the highest possible price for a good",
              "Producing more of a good to meet demand",
              "Lowering prices so everyone can afford a good"],
     "exp": "Because of scarcity, every society must ration. Price, first-come first-served, and coupons are all different methods of rationing."},
    {"ch": 1, "q": "When price is used to ration goods, people have a strong incentive to:",
     "opts": ["Earn income so they can pay the required price",
              "Wait in long lines",
              "Avoid working",
              "Lobby the government for coupons"],
     "exp": "Price rationing allocates goods to those willing to give up other things. That rewards earning income, which in turn encourages productive activity."},
    {"ch": 1, "q": "How many guideposts (key principles) of the economic way of thinking does Gwartney identify?",
     "opts": ["Eight",
              "Five",
              "Ten",
              "Twelve"],
     "exp": "Chapter 1 lists eight guideposts: trade-offs, purposeful choice, incentives, marginal decisions, costly information, secondary effects, subjective value, and testing theories by prediction."},
    {"ch": 1, "q": "A parcel of land could become a hospital, a parking lot, or stay undeveloped. Guidepost 1 says:",
     "opts": ["No option is free; choosing one means a trade-off",
              "Leaving it undeveloped costs nothing",
              "The hospital is always the best choice",
              "Government should decide its use"],
     "exp": "Guidepost 1: the use of scarce resources is costly, so decision-makers face trade-offs. Even 'leaving it alone' gives up the next best use."},
    {"ch": 1, "q": "Pizza, lobster, and steak would give you identical benefits, so you pick the pizza because it's cheapest. This illustrates:",
     "opts": ["Economizing behavior (individuals choose purposefully)",
              "The fallacy of composition",
              "Secondary effects",
              "Value is objective"],
     "exp": "Guidepost 2: people choose purposefully, trying to get the most from limited resources. With equal benefits, they choose the lowest-cost option."},
    {"ch": 1, "q": "A store owner cuts prices to sell off excess inventory, expecting more customers to buy. Which guidepost explains this?",
     "opts": ["Incentives matter",
              "Information is costly",
              "Value is subjective",
              "Association is not causation"],
     "exp": "Guidepost 3: changes in incentives influence choices in predictable ways. A lower price is an incentive to buy more."},
    {"ch": 1, "q": "According to Guidepost 3, which incentives influence human choices?",
     "opts": ["Both monetary and nonmonetary incentives",
              "Only monetary incentives",
              "Only nonmonetary incentives",
              "Only incentives created by government"],
     "exp": "Incentives matter whether they involve money (prices, wages) or not (time, praise, safety, convenience)."},
    {"ch": 1, "q": "In economics, the term 'marginal' describes:",
     "opts": ["The effects of a change in the current situation",
              "The total of all costs and benefits",
              "The average cost per unit",
              "Something that is unimportant"],
     "exp": "Guidepost 4: people decide at the margin, weighing the additional benefit and additional cost of a change from where they are now."},
    {"ch": 1, "q": "A producer's marginal cost is:",
     "opts": ["The cost of producing one additional unit, given its current facility and output",
              "Total cost divided by the number of units",
              "The cost of building a new factory",
              "The fixed cost the firm pays regardless of output"],
     "exp": "Marginal cost is the change in cost from producing one more unit, starting from the current production rate."},
    {"ch": 1, "q": "You compare jeans at a few stores, then stop shopping and buy with the information you have. This reflects which guidepost?",
     "opts": ["Acquiring information is costly",
              "Incentives matter",
              "Value is subjective",
              "The test of a theory is its ability to predict"],
     "exp": "Guidepost 5: information helps us choose, but gathering it takes scarce time. At some point more comparison-shopping isn't worth the trouble."},
    {"ch": 1, "q": "San Francisco banned plastic grocery bags to help the environment, but reusable bags can gather harmful bacteria. This is an example of:",
     "opts": ["A secondary effect",
              "Economizing behavior",
              "A marginal decision",
              "Positive economics"],
     "exp": "Guidepost 6: economic actions often have indirect effects that aren't immediately observable, in addition to their direct effects."},
    {"ch": 1, "q": "In public policy, secondary effects are often:",
     "opts": ["Unintended and overlooked",
              "The main reason a policy is passed",
              "Easy to observe immediately",
              "Always beneficial"],
     "exp": "Secondary effects are indirect impacts that may not be easily or immediately seen, so policymakers frequently miss them."},
    {"ch": 1, "q": "Amir prefers a grass field next to work; Camilla prefers a parking lot and a shorter walk. This illustrates:",
     "opts": ["Value is subjective and varies with individual preferences",
              "Association is not causation",
              "Ceteris paribus",
              "Incentives don't matter"],
     "exp": "Guidepost 7: the value of a good depends on each person's preferences, so the same field is worth different amounts to different people."},
    {"ch": 1, "q": "'The earth is made of marshmallows' is classified as:",
     "opts": ["A positive statement, because it is potentially verifiable (even though it's false)",
              "A normative statement, because it is false",
              "A normative statement, because it is about the earth",
              "Neither positive nor normative"],
     "exp": "Positive statements are about 'what is' and can be tested. They don't have to be correct. Normative statements are about 'what ought to be'."},
    {"ch": 1, "q": "A politician backs a well-meaning policy that ends up causing harm. Which pitfall does this illustrate?",
     "opts": ["Good intentions do not guarantee desirable outcomes",
              "The fallacy of composition",
              "Association is not causation",
              "Violation of ceteris paribus"],
     "exp": "An unsound proposal leads to bad outcomes even when supporters mean well. Politicians may gain from appearing to address a problem even if the policy is ineffective."},
    {"ch": 1, "q": "Cities with more police officers tend to have more crime, so someone concludes police cause crime. This mistake is:",
     "opts": ["Assuming association is causation",
              "The fallacy of composition",
              "Normative reasoning",
              "Economizing behavior"],
     "exp": "Pitfall 3: statistical association alone cannot establish causation. Here, high crime more likely causes cities to hire more police."},
    {"ch": 1, "q": "Microeconomics focuses on:",
     "opts": ["Narrowly defined units, such as individual households or business firms",
              "Highly aggregated markets, such as the market for all labor",
              "Only government decisions",
              "Only international trade"],
     "exp": "Micro looks at individual units; macro looks at highly aggregated outcomes. Watch for the fallacy of composition when moving from micro to macro."},
    # ---------------- Chapter 2: Some Tools of the Economist (added) ----------------
    {"ch": 2, "q": "Which statement about opportunity costs is correct?",
     "opts": ["They are subjective and vary across persons",
              "They are the same for everyone",
              "They only include money paid",
              "They occur only after a choice turns out badly"],
     "exp": "Opportunity cost is the highest valued alternative given up. It's incurred when the choice is made and depends on each person's values."},
    {"ch": 2, "q": "If an option becomes more costly, an individual will be:",
     "opts": ["Less likely to choose it",
              "More likely to choose it",
              "Unaffected, since costs are already sunk",
              "Forced to choose it"],
     "exp": "Raising the opportunity cost of an option makes it less attractive relative to the alternatives."},
    {"ch": 2, "q": "Gwartney classifies which cost of going to college as a NON-MONETARY cost?",
     "opts": ["Forgone earnings from a job you could have had",
              "Tuition",
              "Textbooks",
              "Lab fees"],
     "exp": "College costs include money (tuition, books) and the earnings you give up by not working. That second part is often the bigger cost."},
    {"ch": 2, "q": "You get a fantastic job offer right out of high school. Your opportunity cost of attending college:",
     "opts": ["Rises, so you're less likely to attend",
              "Falls, so you're more likely to attend",
              "Stays the same, since tuition didn't change",
              "Becomes zero"],
     "exp": "The great job is the alternative you'd give up. A more valuable alternative means a higher opportunity cost of college."},
    {"ch": 2, "q": "According to Gwartney, the value of a good or service:",
     "opts": ["Depends on who uses it and the circumstances of when and where it's used",
              "Is fixed and objective once the good exists",
              "Is determined only by its production cost",
              "Is set by the government"],
     "exp": "It's wrong to assume goods have a fixed objective value. Value depends on the user, timing, location, and physical traits."},
    {"ch": 2, "q": "Even when no additional goods are produced, trade creates value by:",
     "opts": ["Moving goods from people who value them less to people who value them more",
              "Ensuring each good is exchanged for one of equal objective value",
              "Raising prices for everyone",
              "Making one party better off at the other's expense"],
     "exp": "Even without producing anything new, trade channels goods to those who value them most, increasing the wealth created by society's resources."},
    {"ch": 2, "q": "Milton and Rose Friedman argued that most economic fallacies come from neglecting the fact that:",
     "opts": ["A voluntary exchange won't take place unless both parties believe they'll benefit",
              "Prices always rise over time",
              "Trade is a zero-sum game",
              "Governments must approve all trades"],
     "exp": "Mutual gain is the foundation of trade. If both sides didn't expect to gain, the voluntary exchange wouldn't happen."},
    {"ch": 2, "q": "Transaction costs are:",
     "opts": ["The time, effort, and resources needed to search out, negotiate, and complete an exchange",
              "The taxes paid on a purchase",
              "The profit earned by the seller",
              "The cost of producing a good"],
     "exp": "Transaction costs are a barrier to trade: they reduce our ability to realize gains from potential exchanges."},
    {"ch": 2, "q": "How does the Internet affect trade?",
     "opts": ["It lowers transaction costs, enhancing trade",
              "It raises transaction costs, reducing trade",
              "It has no effect on transaction costs",
              "It eliminates the need for property rights"],
     "exp": "Online search, reviews, and payment systems make it cheaper to find, negotiate, and complete exchanges, so more mutually beneficial trades happen."},
    {"ch": 2, "q": "Property rights are defined as:",
     "opts": ["The right to use, control, and obtain the benefits from a resource, good, or service",
              "The right to have the government buy your property",
              "The right to use anyone's property freely",
              "The right to set any price the market will not bear"],
     "exp": "Private property rights involve exclusive use, legal protection against invaders, and the right to transfer to another."},
    {"ch": 2, "q": "Why do private owners tend to conserve resources for the future?",
     "opts": ["They gain if the property is expected to increase in value",
              "The law requires them to",
              "They don't bear any costs of using it up",
              "Government pays them to"],
     "exp": "Private owners capture the future value of what they own, so conserving it pays off, especially when it's expected to appreciate."},
    {"ch": 2, "q": "Private property encourages owners to use resources in ways that benefit others because owners:",
     "opts": ["Gain by serving others and bear the opportunity cost of ignoring others' wishes",
              "Are required to share profits with neighbors",
              "Can't sell their property",
              "Receive government subsidies for doing so"],
     "exp": "If an owner ignores what others value, they lose the income those others would have paid. That cost pushes owners toward uses others value."},
    {"ch": 2, "q": "Which is NOT one of the assumptions behind a production possibilities curve?",
     "opts": ["Resources can increase during the period",
              "A fixed amount of productive resources",
              "A given amount of technical knowledge",
              "Full and efficient use of resources"],
     "exp": "The PPC holds resources and technology fixed and assumes full, efficient use. More resources would shift the curve, not move along it."},
    {"ch": 2, "q": "The slope of the production possibilities curve shows:",
     "opts": ["How much of one good must be given up to produce more of the other",
              "The total value of all output",
              "The price of each good",
              "How much labor is unemployed"],
     "exp": "The slope is the opportunity cost of producing more of one product, measured in units of the other."},
    {"ch": 2, "q": "With 10 hours of study, Susan can get a B in English and a B in economics, or an A in English and a D in economics. Her opportunity cost of raising English from B to A is:",
     "opts": ["Her economics grade falling from B to D",
              "Nothing, since study time is free",
              "Her English grade falling from A to B",
              "Studying more than 10 hours"],
     "exp": "Moving along her PPC from T to U, she gains in English only by shifting hours away from economics. The lost economics grade is the opportunity cost."},
    {"ch": 2, "q": "Which of these could shift a country's PPC outward?",
     "opts": ["An improvement in the rules under which the economy functions",
              "Moving workers from farming to manufacturing",
              "Leaving some factories idle",
              "Higher prices for consumer goods"],
     "exp": "The four outward shifters are: more resources, better technology, improved rules (institutions), and working harder by giving up leisure."},
    {"ch": 2, "q": "An entrepreneur is a person who:",
     "opts": ["Decides what resources to use, how to combine them, and what goods to produce",
              "Works for a government agency",
              "Only invests money in the stock market",
              "Sets prices for an entire industry"],
     "exp": "When entrepreneurs create goods valued highly relative to their cost, they succeed personally and expand the economy's production possibilities."},
    {"ch": 2, "q": "In the production possibilities framework, economic growth is:",
     "opts": ["An outward shift in the curve over time",
              "A movement from one point to another along the curve",
              "A movement to a point inside the curve",
              "A curve that gets steeper"],
     "exp": "Growth expands what the economy can produce. The faster the curve shifts outward, the faster the growth."},
    # ---------------- Chapter 5: Difficult Cases for the Market (added) ----------------
    {"ch": 5, "q": "Economists use efficiency to judge actions because efficient use of resources implies:",
     "opts": ["The maximum value of output from the resource base",
              "The lowest possible prices",
              "Equal incomes for everyone",
              "Zero pollution"],
     "exp": "Efficiency means getting the most value from limited resources: undertaking actions whose benefits exceed costs and avoiding those whose costs exceed benefits."},
    {"ch": 5, "q": "At an output level where marginal benefit EXCEEDS marginal cost, the activity should be:",
     "opts": ["Expanded, because worthwhile units aren't being undertaken",
              "Reduced, because too much is being produced",
              "Left unchanged, because it's efficient",
              "Stopped entirely"],
     "exp": "If MB > MC, the next unit adds more value than it costs. Expanding until MB = MC captures those gains."},
    {"ch": 5, "q": "At an output level where marginal cost EXCEEDS marginal benefit:",
     "opts": ["Units are being produced that cost more than they're worth, so output is too high",
              "Output is too low",
              "The activity is efficient",
              "Marginal benefit must rise"],
     "exp": "Producing units where MC > MB wastes resources. Efficiency requires cutting back to where MB = MC."},
    {"ch": 5, "q": "'If it's worth doing, it's worth doing imperfectly' means:",
     "opts": ["At some point, the gains from doing something better aren't worth the cost",
              "Quality never matters",
              "You should never finish a task",
              "Perfection is always worth the cost"],
     "exp": "Even worthy activities can be pushed beyond the efficient level. This applies to people and governments alike."},
    {"ch": 5, "q": "From an efficiency standpoint, eliminating ALL air and water pollution:",
     "opts": ["Generally doesn't make sense, because the cost of removing the last bits would exceed the benefit",
              "Always makes sense, because pollution is harmful",
              "Is required for efficiency",
              "Has no cost"],
     "exp": "Like making the highest possible grade or zero traffic fatalities, perfection is rarely worth its cost. The efficient level is where MB = MC."},
    {"ch": 5, "q": "Providing a stable monetary and financial environment is part of government's:",
     "opts": ["Productive function",
              "Rationing function",
              "Rent-seeking function",
              "Regulatory failure"],
     "exp": "The productive function provides a limited set of goods that are hard to supply through markets. The protective function covers protecting people and property and enforcing contracts. (Note: Ch. 6's summary slide groups monetary stability with the protective function; Ch. 5 classifies it as productive.)"},
    {"ch": 5, "q": "The most fundamental function of government is:",
     "opts": ["Protecting individuals and their property against acts of aggression",
              "Producing consumer goods",
              "Setting prices in markets",
              "Redistributing income"],
     "exp": "The protective function includes maintaining a legal structure that enforces contracts and settles disputes."},
    {"ch": 5, "q": "If producers can restrict supply or limit entry into a market, compared to the competitive outcome:",
     "opts": ["Output will be lower and price will be higher",
              "Output will be higher and price will be lower",
              "Output and price will both be higher",
              "Nothing changes"],
     "exp": "With restricted supply (S2), output falls from Q1 to Q2 and price rises from P1 to P2: too few units at too high a price."},
    {"ch": 5, "q": "External costs (like pollution) arise mainly because:",
     "opts": ["Property rights are imperfectly defined or enforced",
              "Prices are too high",
              "Government provides too many public goods",
              "Consumers have perfect information"],
     "exp": "When people's property can be harmed without their consent, those costs aren't registered in the market."},
    {"ch": 5, "q": "When external costs are present, the market supply curve:",
     "opts": ["Understates the true cost of production",
              "Overstates the true cost of production",
              "Accurately reflects all costs",
              "Becomes vertical"],
     "exp": "Since some costs fall on others, producers don't count them. Units get produced that are worth less than their full cost."},
    {"ch": 5, "q": "When it isn't realistic to define property rights (many people are affected), what may be the best way to handle external costs such as emissions?",
     "opts": ["Government regulations requiring devices that limit emissions",
              "Doing nothing, since markets always correct themselves",
              "Banning all production",
              "Subsidizing the polluting firms"],
     "exp": "Defining and enforcing property rights works with few parties. With large numbers, emission-limiting regulations, or creative arrangements, may be the best option."},
    {"ch": 5, "q": "When external benefits are present, the market demand curve:",
     "opts": ["Understates the total value of the output",
              "Overstates the total value of the output",
              "Shifts to the right automatically",
              "Reflects all benefits accurately"],
     "exp": "Benefits to nonparticipants aren't counted by buyers, so some units worth more than their cost aren't produced."},
    {"ch": 5, "q": "If all external benefits were counted, the demand curve would shift to D2. Compared with the market outcome, output and price would be:",
     "opts": ["Output higher and price higher",
              "Output lower and price lower",
              "Output higher and price lower",
              "Unchanged"],
     "exp": "Counting all benefits raises demand, so output rises from Q1 to Q2 and price rises from P1 to P2. The market alone produces too few units."},
    {"ch": 5, "q": "Which of these is an example of a public good?",
     "opts": ["A mosquito abatement program",
              "A pizza",
              "A haircut",
              "A new car"],
     "exp": "Mosquito control is nonrival and nonexcludable: everyone in the area benefits at once, and nonpayers can't be excluded. National defense and broadcast signals are other examples."},
    {"ch": 5, "q": "What distinguishes a good as a public good?",
     "opts": ["Its characteristics (nonrival and nonexcludable), not the sector that produces it",
              "Whether government produces it",
              "Whether it's free",
              "Whether it's sold in a market"],
     "exp": "Government can provide private goods and markets can provide public goods. The good's traits define it."},
    {"ch": 5, "q": "The consumer's information problem is minimal when the item is:",
     "opts": ["A repeat-purchase item bought often from the same seller",
              "Bought once in a lifetime",
              "Difficult to evaluate on inspection",
              "Capable of serious hidden side effects"],
     "exp": "Frequent buyers learn about quality, and sellers want repeat business. Problems arise with rarely purchased, hard-to-evaluate, or potentially harmful goods."},
    {"ch": 5, "q": "Consumer Reports, brand names, franchises, and online reviews show that:",
     "opts": ["Information can be a profit opportunity, since consumers will pay for better information",
              "Markets can never solve information problems",
              "Government must provide all product information",
              "Information is free"],
     "exp": "Because consumers value better information, businesses profit by providing expert evaluations and reliable standardized quality."},
    # ---------------- Chapter 6: The Economics of Political Action (added) ----------------
    {"ch": 6, "q": "Transfer payments are:",
     "opts": ["Payments that tax income from some people and transfer it to others",
              "Payments for government purchases of goods",
              "Interest paid on government bonds",
              "Wages paid to government employees"],
     "exp": "Transfer payments (like Social Security) redistribute income rather than buying output, and they have grown substantially over time."},
    {"ch": 6, "q": "Which is a SIMILARITY between government and markets?",
     "opts": ["Scarcity and competition are present in both",
              "Payment always corresponds to consumption in both",
              "Both are based on unanimous agreement",
              "Both distribute influence according to income"],
     "exp": "Resources the government uses are unavailable for other goods, even if the good is free to some consumers. And competition exists in both sectors."},
    {"ch": 6, "q": "Voters must choose candidates who represent a whole bundle of positions. This 'bundle-purchase' problem:",
     "opts": ["Limits individual voters' power to make their preferences count on specific issues",
              "Is common in markets",
              "Gives voters more choice than markets do",
              "Only affects politicians"],
     "exp": "In markets you can buy exactly the items you want. In politics you get a candidate's entire package, so specific preferences are hard to express."},
    {"ch": 6, "q": "Private-sector action is based on ___, while democratic public-sector action is based on ___.",
     "opts": ["Mutual agreement; majority rule",
              "Majority rule; mutual agreement",
              "Force; voluntary exchange",
              "Prices; lotteries"],
     "exp": "Market trades happen only if both sides agree. In politics, a majority can impose decisions on the minority."},
    {"ch": 6, "q": "In the political sector, who tends to have the most influence?",
     "opts": ["Those most able and willing to use their time, persuasion, organization, and contributions to help politicians get votes",
              "Those with the highest incomes, exactly as in markets",
              "Every voter equally",
              "Bureaucrats only"],
     "exp": "Influence is distributed differently than in markets: political activity and support, not just income, buy political influence."},
    {"ch": 6, "q": "Public choice analysis views the political process as an interaction among which three groups?",
     "opts": ["Voter-taxpayers, politicians, and bureaucrats",
              "Consumers, producers, and banks",
              "Courts, Congress, and the president",
              "Unions, businesses, and lobbyists"],
     "exp": "Public choice applies economics to politics, assuming self-interested behavior in both markets and government."},
    {"ch": 6, "q": "According to public choice analysis, the primary motivation of politicians is:",
     "opts": ["Winning elections",
              "Maximizing economic efficiency",
              "Reducing the size of government",
              "Maximizing profits"],
     "exp": "Votes are the lifeblood of the politician, just as profits are for the market entrepreneur."},
    {"ch": 6, "q": "Government bureaucrats' interests are generally served by:",
     "opts": ["Larger budgets and program expansion",
              "Smaller budgets and fewer programs",
              "Cost cutting that reduces their staff",
              "Ending the programs they run"],
     "exp": "Bureaucrats seek promotions, job security, and power, and their interests often align with the interest groups they serve."},
    {"ch": 6, "q": "Road project: Plan B makes each voter pay in proportion to the benefits they receive. What happens in the vote?",
     "opts": ["It passes unanimously, since every voter gains",
              "It fails 3 to 2",
              "It passes 3 to 2",
              "It fails unanimously"],
     "exp": "When costs are allocated in proportion to benefits, everyone gains from a productive project. That's when good politics and efficiency are in harmony."},
    {"ch": 6, "q": "When a project's benefits are widespread but its costs are concentrated, the political process tends to:",
     "opts": ["Reject projects even when they're productive",
              "Adopt projects even when they're counterproductive",
              "Make efficient decisions",
              "Have no bias"],
     "exp": "This is type 4. The few who bear concentrated costs fight hard, while the many who'd gain a little pay little attention."},
    {"ch": 6, "q": "When benefits and costs are BOTH widespread (or both concentrated), representative government tends to:",
     "opts": ["Undertake productive projects and reject unproductive ones",
              "Adopt inefficient projects",
              "Reject all projects",
              "Ignore the projects"],
     "exp": "Types 1 and 3 work reasonably well: the people who gain and the people who pay weigh in similarly, so politics tracks efficiency."},
    {"ch": 6, "q": "A bill combines a post office in district A, a harbor in B, and a stadium in C. Each project nets its own district +$10 but costs every other district $3, so the bill's total is -$6. How can it still pass?",
     "opts": ["Representatives of A, B, and C trade votes (logrolling) to form a majority",
              "Districts D and E vote for it",
              "It can't pass, since the total is negative",
              "The president passes it without a vote"],
     "exp": "Vote trading lets a majority pass a package of projects that each benefit a few districts, even though the whole package is counterproductive."},
    {"ch": 6, "q": "Politicians often favor established firms (like taxi companies over Uber) because established firms:",
     "opts": ["Have stronger records of political contributions and know lobbying techniques",
              "Are always more efficient",
              "Pay lower taxes",
              "Have more customers"],
     "exp": "Logrolling and pork-barrel politics strengthen the special interest effect, favoring politically connected incumbents over innovative upstarts."},
    {"ch": 6, "q": "What is the effect of widespread rent seeking on an economy?",
     "opts": ["It diverts resources away from productive activities, so output falls below potential",
              "It increases output above potential",
              "It has no effect on output",
              "It improves the efficiency of government"],
     "exp": "Resources spent lobbying for favors aren't spent producing goods. The more government power favors some at others' expense, the more rent seeking occurs."},
    {"ch": 6, "q": "Why do government-operated firms and agencies tend to be less efficient?",
     "opts": ["No profit motive to keep costs low and no bankruptcy process to weed out inefficient producers",
              "Government workers are less talented",
              "They face too much competition",
              "They are required to make a profit"],
     "exp": "Public managers rarely gain personally from cost cuts and spend other people's money, so they have less incentive to be cost-conscious."},
    {"ch": 6, "q": "Mattel helped write costly toy-testing rules into the 2008 Consumer Product Safety Improvement Act, raising smaller rivals' costs. This is an example of:",
     "opts": ["Crony capitalism",
              "A public good",
              "Comparative advantage",
              "A positive externality"],
     "exp": "Crony capitalism allocates resources by political favors rather than consumer preferences. Mattel gained while rivals and used-toy sellers like Goodwill were pushed out."},
    # ---------------- Chapter 7: Taking the Nation's Economic Pulse (added) ----------------
    {"ch": 7, "q": "Gross Domestic Product (GDP) is:",
     "opts": ["The market value of final goods and services produced within a country during a specific period",
              "The total value of all goods sold in a country, including used goods",
              "The income earned by a country's citizens anywhere in the world",
              "The value of all intermediate and final goods produced"],
     "exp": "GDP counts final goods and services, produced within the country's borders, in a given period (usually a year). It's the most widely used indicator of economic performance."},
    {"ch": 7, "q": "What are the two ways of measuring GDP?",
     "opts": ["The expenditure approach and the resource cost-income approach",
              "The CPI approach and the GDP deflator approach",
              "The micro approach and the macro approach",
              "The nominal approach and the real approach"],
     "exp": "GDP measures both output and income: you can total spending on final goods, or total the incomes and costs generated by producing them."},
    {"ch": 7, "q": "In the expenditure approach, net exports equal:",
     "opts": ["Exports minus imports",
              "Imports minus exports",
              "Exports plus imports",
              "Exports minus government purchases"],
     "exp": "The four components are consumption, gross private investment, government purchases, and net exports (exports minus imports)."},
    {"ch": 7, "q": "Under the expenditure approach, an increase in business inventories is counted in:",
     "opts": ["Gross private investment",
              "Consumption",
              "Government purchases",
              "Net exports"],
     "exp": "Gross private investment includes new structures, equipment, and changes in inventories."},
    {"ch": 7, "q": "The sum of employee compensation, self-employment income, rents, interest, and corporate profits equals:",
     "opts": ["National income",
              "Nominal GDP",
              "Net exports",
              "Personal consumption"],
     "exp": "These are the direct cost-income components in the resource cost-income approach."},
    {"ch": 7, "q": "In GDP statistics, the term 'real' means:",
     "opts": ["Adjusted for inflation",
              "Measured in current dollars",
              "Including only physical goods",
              "Excluding government spending"],
     "exp": "Real figures remove the effect of price changes so you can compare actual output across time."},
    {"ch": 7, "q": "A price index measures:",
     "opts": ["The cost of a market basket at a point in time relative to its cost in a base period",
              "The total quantity of goods produced",
              "The price of one specific product",
              "The interest rate on loans"],
     "exp": "Price indexes like the CPI and GDP deflator compare the cost of the same bundle across periods to track inflation."},
    {"ch": 7, "q": "The chained CPI differs from the traditional CPI because it:",
     "opts": ["Adjusts the market basket monthly to reflect substitution away from goods that became relatively more expensive",
              "Includes all goods in GDP",
              "Only measures food and energy prices",
              "Is calculated once every ten years"],
     "exp": "By accounting for substitution, the chained CPI usually shows slightly lower inflation than the traditional CPI."},
    {"ch": 7, "q": "Compared with the traditional CPI, the chained CPI and GDP deflator generally show inflation that is:",
     "opts": ["About 0.2 to 0.3 percentage points lower",
              "About 2 to 3 percentage points higher",
              "Exactly the same",
              "About 5 percentage points lower"],
     "exp": "More frequent updating of the bundle and substitution adjustments lead to slightly lower measured inflation."},
    {"ch": 7, "q": "Nominal GDP is $1,000 billion and the GDP deflator is 125 (base year = 100). Real GDP in base-year dollars is:",
     "opts": ["$800 billion",
              "$1,250 billion",
              "$875 billion",
              "$1,000 billion"],
     "exp": "Real GDP = Nominal GDP x (base index / current index) = 1,000 x (100 / 125) = $800 billion."},
    {"ch": 7, "q": "Your parents earned $40,000 in a year when the CPI was 100. The CPI is now 150. In today's dollars, their income equals:",
     "opts": ["$60,000",
              "$26,667",
              "$40,000",
              "$90,000"],
     "exp": "Inflate earlier data: $40,000 x (150 / 100) = $60,000. This expresses old figures in today's purchasing power."},
    {"ch": 7, "q": "The GDP deflator rose from 120 to 126 over the year. The inflation rate was:",
     "opts": ["5%",
              "6%",
              "4.8%",
              "26%"],
     "exp": "Inflation rate = (126 - 120) / 120 x 100 = 5%. Inflation can be calculated with either the CPI or the GDP deflator."},
    {"ch": 7, "q": "Income from illegal activities or hidden to avoid taxes is a GDP shortcoming known as:",
     "opts": ["The underground economy",
              "Nonmarket production",
              "Economic 'bads'",
              "Quality variation"],
     "exp": "Concealed activity isn't recorded, so GDP understates actual production."},
    {"ch": 7, "q": "Everyone works longer hours and takes less vacation, raising output. Why might GDP overstate the gain in well-being?",
     "opts": ["GDP excludes leisure and the human costs of production",
              "GDP counts leisure as output",
              "GDP subtracts wages",
              "GDP only counts government output"],
     "exp": "GDP counts the extra goods but makes no deduction for the leisure given up or the strain of producing them."},
    {"ch": 7, "q": "A factory's pollution harms a nearby community. How does GDP handle this?",
     "opts": ["It makes no adjustment for harmful side effects ('bads')",
              "It subtracts the damage from GDP",
              "It adds the damage to GDP",
              "It excludes the factory's output from GDP"],
     "exp": "GDP doesn't subtract harmful side effects of production, consumption, or destructive acts of people and nature."},
    {"ch": 7, "q": "Free apps replace paid maps, cameras, and music. How might GDP be affected?",
     "opts": ["It may understate well-being, and GDP could even fall",
              "GDP rises by the value of the free apps",
              "GDP perfectly captures the improvement",
              "GDP isn't affected at all"],
     "exp": "Technology in the information age improves well-being a lot but has less impact on GDP, sometimes reducing it."},
    {"ch": 7, "q": "Despite its shortcomings, real GDP per person is:",
     "opts": ["A broad indicator of living standards",
              "Unrelated to living standards",
              "A precise measure of happiness",
              "Only useful for measuring government size"],
     "exp": "As real per capita GDP has risen, life expectancy and leisure rose while illiteracy and infant mortality fell."},
    {"ch": 7, "q": "Per capita GDP is calculated as:",
     "opts": ["GDP divided by the size of the population",
              "GDP divided by the number of workers",
              "GDP minus population",
              "GDP times the inflation rate"],
     "exp": "In 2023, U.S. real per capita GDP was 3.4 times its 1960 level and 7.5 times its 1930 level."},
    # ---------------- Chapter 8: Fluctuations, Unemployment, Inflation (added) ----------------
    {"ch": 8, "q": "Since 1960, the U.S. growth rate of real GDP has averaged approximately:",
     "opts": ["3% per year",
              "1% per year",
              "7% per year",
              "10% per year"],
     "exp": "Growth is about 3% a year on average, but it's unstable, with periodic recessions of declining real GDP."},
    {"ch": 8, "q": "A depression is:",
     "opts": ["A prolonged and very severe recession",
              "Any decline in GDP lasting one month",
              "A period of rapid growth",
              "A rise in the inflation rate"],
     "exp": "A recession is a downturn with declining real GDP and rising unemployment. A depression is an especially long and severe one."},
    {"ch": 8, "q": "When most businesses operate at capacity and real GDP is growing rapidly, the economy is at a:",
     "opts": ["Peak (boom)",
              "Recessionary trough",
              "Contraction",
              "Depression"],
     "exp": "After the peak, business conditions slow and the contraction (recessionary) phase begins."},
    {"ch": 8, "q": "A person who is not working but applied for a job at Target last week is:",
     "opts": ["Unemployed",
              "Employed",
              "Not in the labor force",
              "Discouraged and not counted"],
     "exp": "Actively seeking a job while not working counts as unemployed."},
    {"ch": 8, "q": "A homemaker working 70 hours a week preparing meals and doing household tasks is classified as:",
     "opts": ["Not in the labor force",
              "Employed",
              "Unemployed",
              "Self-employed"],
     "exp": "Household production isn't paid market work, so the homemaker isn't counted as employed or unemployed."},
    {"ch": 8, "q": "Which person counts as EMPLOYED?",
     "opts": ["Someone working 15+ hours a week without pay in a family-operated business",
              "Someone working 5 hours a week without pay in a family business",
              "A retired Social Security recipient",
              "A full-time student who isn't working"],
     "exp": "Employed means working for pay at least one hour a week, being self-employed, or working 15+ unpaid hours in a family enterprise."},
    {"ch": 8, "q": "Population age 16+ = 250M and employed = 152M. The employment-population ratio is:",
     "opts": ["60.8%",
              "64%",
              "95%",
              "5%"],
     "exp": "Employment-population ratio = employed / population 16+ = 152 / 250 = 60.8%."},
    {"ch": 8, "q": "Unemployment that rises because of a general downturn in business activity is:",
     "opts": ["Cyclical unemployment",
              "Frictional unemployment",
              "Structural unemployment",
              "Seasonal unemployment"],
     "exp": "Cyclical unemployment reflects business cycle conditions. It's absent at full employment."},
    {"ch": 8, "q": "Which factors influence the natural rate of unemployment?",
     "opts": ["Demographics (like the share of young workers) and public policy (like unemployment benefits)",
              "Only the money supply",
              "Only the inflation rate",
              "Nothing; it's fixed forever"],
     "exp": "The natural rate reflects job shopping in a dynamic economy. It's achievable and sustainable, and it changes with demographics and policy."},
    {"ch": 8, "q": "True or false: when full employment is present, the unemployment rate will be zero.",
     "opts": ["False: frictional and structural unemployment remain",
              "True: everyone has a job",
              "True: only cyclical unemployment remains",
              "False: cyclical unemployment is at its highest"],
     "exp": "Full employment means unemployment is at its natural rate, with normal job search and skill mismatches still present."},
    {"ch": 8, "q": "Potential output is:",
     "opts": ["The maximum sustainable output consistent with the economy's resource base and institutions",
              "The highest output ever reached, even briefly",
              "Output when unemployment is zero",
              "Output during a recession"],
     "exp": "Actual and potential output are equal when the economy is at full employment."},
    {"ch": 8, "q": "According to economists, what causes inflation?",
     "opts": ["Aggregate demand rising faster than supply, and rapid growth of the money supply",
              "Falling aggregate demand",
              "Low unemployment benefits",
              "Rising productivity"],
     "exp": "Prices rise when there is 'too much money chasing too few goods.' Nearly all economists link rapid money growth to inflation."},
    # ---------------- Chapter 9: Basic Macroeconomic Markets (added) ----------------
    {"ch": 9, "q": "Which is NOT one of the four key markets that coordinate the circular flow?",
     "opts": ["The housing market",
              "The goods and services market",
              "The loanable funds market",
              "The foreign exchange market"],
     "exp": "The four markets are goods and services, resources, loanable funds, and foreign exchange."},
    {"ch": 9, "q": "Monetary policy is:",
     "opts": ["The deliberate control of the money supply (and sometimes credit conditions) to achieve macroeconomic goals",
              "The use of taxes and government spending to achieve macro goals",
              "Government rules on bank fees",
              "Setting the exchange rate by law"],
     "exp": "Fiscal policy uses taxes and spending. Monetary policy uses the money supply. The basic model initially holds both constant."},
    {"ch": 9, "q": "The aggregate demand curve shows:",
     "opts": ["The quantities of domestically produced goods and services buyers will purchase at different price levels",
              "The total supply of goods at each price level",
              "The demand for money at each interest rate",
              "Demand for imported goods only"],
     "exp": "AD slopes downward: a lower price level means a larger quantity of goods and services demanded."},
    {"ch": 9, "q": "In macroeconomics, the 'short run' is a period during which:",
     "opts": ["Some prices, especially in resource markets, are fixed by prior contracts",
              "All prices adjust instantly",
              "Output can't change",
              "Technology improves"],
     "exp": "Because some prices are locked in, people can't immediately adjust to unexpected changes in the price level. In the long run they can."},
    {"ch": 9, "q": "If the price level is ABOVE the short-run equilibrium level (where AD meets SRAS):",
     "opts": ["Excess supply will push prices down",
              "Excess demand will push prices up",
              "Output will rise to meet demand",
              "The economy is in long-run equilibrium"],
     "exp": "Above equilibrium, sellers want to supply more than buyers want, so prices fall. Below it, excess demand pushes prices up."},
    {"ch": 9, "q": "About what share of U.S. production costs are labor costs?",
     "opts": ["About 70%",
              "About 10%",
              "About 30%",
              "About 95%"],
     "exp": "Labor is by far the largest component of the resource market."},
    {"ch": 9, "q": "From a lender's viewpoint, interest is:",
     "opts": ["A premium received for waiting (delaying current spending)",
              "The cost paid for earlier availability",
              "A tax paid to the government",
              "The inflation rate"],
     "exp": "For borrowers, interest is the cost of getting funds earlier. For lenders, it's the reward for waiting."},
    {"ch": 9, "q": "The difference between the money interest rate and the real interest rate is the:",
     "opts": ["Inflationary premium",
              "Risk premium",
              "Exchange rate",
              "Profit margin"],
     "exp": "The inflationary premium reflects the expected decline in the dollar's purchasing power while the loan is outstanding."},
    {"ch": 9, "q": "If actual inflation turns out LOWER than anticipated:",
     "opts": ["Lenders gain at the expense of borrowers",
              "Borrowers gain at the expense of lenders",
              "Neither gains nor loses",
              "Both gain equally"],
     "exp": "Borrowers repay with dollars worth more than expected, and the inflation premium they paid turns out too high."},
    {"ch": 9, "q": "When domestic demand for loanable funds is weak and the real interest rate is low:",
     "opts": ["Capital flows out toward markets with higher expected returns",
              "Capital flows in from abroad",
              "Interest rates must rise immediately",
              "The trade deficit grows"],
     "exp": "Investors seek the best returns globally. Strong domestic demand and high rates attract a capital inflow instead."},
    {"ch": 9, "q": "In recent years, much of the capital inflow to the U.S. has financed federal deficits. The result has been:",
     "opts": ["Higher current consumption and lower investment, slowing growth",
              "Higher investment and faster growth",
              "A trade surplus",
              "Lower federal spending"],
     "exp": "Borrowing to support current consumption reduces capital formation. Like a family, a nation can't solve financial problems by borrowing more to keep consuming."},
    {"ch": 9, "q": "If the U.S. dollar appreciates against the euro:",
     "opts": ["Fewer dollars are needed to buy a euro, and net exports tend to fall",
              "More dollars are needed to buy a euro, and net exports rise",
              "Fewer dollars are needed to buy a euro, and net exports rise",
              "Nothing happens to net exports"],
     "exp": "A stronger dollar makes foreign goods cheaper for Americans and U.S. goods pricier for foreigners, so imports rise and exports fall."},
    {"ch": 9, "q": "If the inflation rate increases and stays higher for a long time, what happens to interest rates?",
     "opts": ["The nominal rate rises; the real rate stays about the same",
              "The real rate rises; the nominal rate stays the same",
              "Both fall",
              "Neither changes"],
     "exp": "Once higher inflation is expected, lenders add a bigger inflation premium (e.g., 6% real + 5% expected inflation = 11% nominal)."},
    # ---------------- Chapter 10: Dynamic Change & the AD-AS Model (added) ----------------
    {"ch": 10, "q": "An 'anticipated' change in the economy is one that:",
     "opts": ["Is fully expected, so decision makers can adjust before it occurs",
              "Catches people by surprise",
              "Only affects the long run",
              "Is caused by government"],
     "exp": "Unanticipated changes catch people by surprise and disrupt equilibrium. Anticipated ones are built into plans and contracts."},
    {"ch": 10, "q": "An increase in the EXPECTED rate of inflation will tend to:",
     "opts": ["Increase aggregate demand",
              "Decrease aggregate demand",
              "Shift LRAS to the right",
              "Have no effect on AD"],
     "exp": "If people expect prices to rise, they buy more now, shifting AD right. Expected inflation also reduces SRAS, since resource costs rise."},
    {"ch": 10, "q": "Higher real incomes in other countries will:",
     "opts": ["Increase U.S. aggregate demand, since foreigners buy more U.S. exports",
              "Decrease U.S. aggregate demand",
              "Shift U.S. LRAS left",
              "Have no effect on the U.S."],
     "exp": "Richer foreigners demand more U.S. goods, raising net exports and AD."},
    {"ch": 10, "q": "A reduction in EXPECTED inflation would:",
     "opts": ["Shift SRAS to the right, without changing LRAS",
              "Shift LRAS to the right",
              "Shift both LRAS and SRAS to the left",
              "Shift AD to the right"],
     "exp": "SRAS shifters include resource prices, expected inflation, and supply shocks. LRAS depends on resources, technology, and institutions. It would also tend to shift AD to the left, not right, since lower expected inflation reduces current buying."},
    {"ch": 10, "q": "If an adverse supply shock (like a higher oil price) turns out to be PERMANENT:",
     "opts": ["LRAS shifts left and the economy's productive potential shrinks",
              "The economy returns to its original equilibrium",
              "LRAS shifts right",
              "Only AD is affected"],
     "exp": "A temporary shock fades as resource prices fall back. A permanent one reduces potential output, so LRAS shifts left."},
    {"ch": 10, "q": "When the actual and expected rates of inflation are equal:",
     "opts": ["Inflation is built into contracts, and relative prices between resource and product markets don't change",
              "Firms earn unusually high profits and expand output",
              "Firms incur losses and cut output",
              "Unemployment rises above the natural rate"],
     "exp": "Correctly anticipated inflation raises all prices together, so profit margins and output aren't disrupted."},
    {"ch": 10, "q": "According to the AD-AS model, the two causes of economic BOOMS are:",
     "opts": ["Unanticipated increases in AD and favorable supply shocks",
              "Anticipated increases in AD and higher taxes",
              "Higher resource prices and lower real wealth",
              "Unfavorable supply shocks and falling AD"],
     "exp": "Booms happen when goods prices are high relative to resource prices and costs. Recessions are the mirror image."},
    {"ch": 10, "q": "After a temporary favorable supply shock, people who know their high income won't last tend to:",
     "opts": ["Save more, which can lower interest rates and boost capital formation",
              "Spend all of the extra income immediately",
              "Borrow more",
              "Stop working"],
     "exp": "Since the higher income is temporary, saving rises. With an unfavorable shock, households may dip into past savings instead."},
]

CHAPTER_NAMES = {
    1: "The Economic Approach",
    2: "Some Tools of the Economist",
    5: "Difficult Cases for the Market & Role of Government",
    6: "The Economics of Political Action",
    7: "Taking the Nation's Economic Pulse (GDP)",
    8: "Fluctuations, Unemployment & Inflation",
    9: "Basic Macroeconomic Markets",
    10: "Dynamic Change & the AD-AS Model",
}

WIDTH = 78


def wrap(text, indent=""):
    return textwrap.fill(text, WIDTH, initial_indent=indent, subsequent_indent=indent)


def load_missed():
    try:
        with open(SAVE_FILE) as f:
            return set(json.load(f))
    except (OSError, ValueError):
        return set()


def save_missed(missed):
    try:
        with open(SAVE_FILE, "w") as f:
            json.dump(sorted(missed), f)
    except OSError:
        pass


def ask(idx, number, total):
    """Ask one question. Returns True if answered correctly, None if the user quit."""
    item = QUESTIONS[idx]
    correct = item["opts"][0]
    opts = item["opts"][:]
    random.shuffle(opts)
    letters = "abcd"[:len(opts)]

    print("\n" + "-" * WIDTH)
    print(f"[{number}/{total}]  Ch. {item['ch']}: {CHAPTER_NAMES[item['ch']]}")
    print(wrap(item["q"]))
    for letter, opt in zip(letters, opts):
        print(textwrap.fill(opt, WIDTH, initial_indent=f"   {letter}) ", subsequent_indent="      "))

    while True:
        ans = input("Your answer (or q to quit): ").strip().lower()
        if ans == "q":
            return None
        if ans in letters and ans:
            break
        print(f"  Type one of: {', '.join(letters)}")

    chosen = opts[letters.index(ans)]
    right_letter = letters[opts.index(correct)]
    if chosen == correct:
        print("  Correct!")
        print(wrap(item["exp"], "  "))
        return True
    print(f"  Not quite. Answer: {right_letter}) {correct}")
    print(wrap(item["exp"], "  "))
    return False


def run_round(pool):
    """Run through the pool; missed questions repeat at the end until correct."""
    saved_missed = load_missed()
    queue = pool[:]
    random.shuffle(queue)
    first_try_right = 0
    first_attempt = set()
    per_ch = {}
    number = 0

    while queue:
        idx = queue.pop(0)
        number += 1
        result = ask(idx, number, number + len(queue))
        if result is None:
            break
        ch = QUESTIONS[idx]["ch"]
        if idx not in first_attempt:
            first_attempt.add(idx)
            right, seen = per_ch.get(ch, (0, 0))
            per_ch[ch] = (right + (1 if result else 0), seen + 1)
            if result:
                first_try_right += 1
                saved_missed.discard(idx)  # nailed it first try: off the weak list
        if not result:
            saved_missed.add(idx)
            queue.append(idx)  # comes back later in the round

    save_missed(saved_missed)

    if first_attempt:
        n = len(first_attempt)
        print("\n" + "=" * WIDTH)
        print(f"First-try score: {first_try_right}/{n}  ({100 * first_try_right // n}%)")
        for ch in sorted(per_ch):
            right, seen = per_ch[ch]
            flag = "  <- review this" if right / seen < 0.75 else ""
            print(f"  Ch. {ch}: {right}/{seen}{flag}")
        print(f"Questions saved to weak spots: {len(saved_missed)}")
        print("=" * WIDTH)


def choose_chapters():
    chapters = sorted(CHAPTER_NAMES)
    print("\nChapters:")
    for ch in chapters:
        count = sum(1 for q in QUESTIONS if q["ch"] == ch)
        print(f"  {ch}: {CHAPTER_NAMES[ch]} ({count} questions)")
    raw = input("Enter chapter numbers separated by spaces (blank = all): ").strip()
    if not raw:
        return chapters
    picked = []
    for part in raw.replace(",", " ").split():
        if part.isdigit() and int(part) in CHAPTER_NAMES:
            picked.append(int(part))
    return picked or chapters


def main():
    print("=" * WIDTH)
    print("  MACROECONOMICS PRACTICE QUIZ  (Gwartney 18e, Ch. 1, 2, 5-10)")
    print("=" * WIDTH)
    while True:
        missed = load_missed()
        print("\nMenu:")
        print("  1) Practice all chapters")
        print("  2) Pick chapters")
        print(f"  3) Weak spots only ({len(missed)} saved)")
        print("  4) Clear weak spots")
        print("  5) Quit")
        choice = input("> ").strip()

        if choice == "1":
            run_round(list(range(len(QUESTIONS))))
        elif choice == "2":
            chs = choose_chapters()
            pool = [i for i, q in enumerate(QUESTIONS) if q["ch"] in chs]
            run_round(pool)
        elif choice == "3":
            pool = [i for i in missed if i < len(QUESTIONS)]
            if not pool:
                print("No weak spots saved yet. Nice!")
            else:
                run_round(pool)
        elif choice == "4":
            save_missed(set())
            print("Weak spots cleared.")
        elif choice == "5":
            print("Good luck Monday!")
            break


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nGood luck Monday!")
